import {
  User,
  Lock,
  PieChart,
  Clock,
  ArrowRight,
  ArrowLeft,
  Loader2,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  KeyRound,
  ShieldCheck,
  Check,
  Search,
  LayoutGrid,
  List,
  Table,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Zap,
  Plus,
  MoreVertical,
  TrendingUp,
  TrendingDown,
  HelpCircle,
  Users,
  Settings,
  FileText,
  Building,
  MapPin,
  Calendar,
  Briefcase,
  LogOut,
  Menu,
  Grid,
  Filter,
  SlidersHorizontal,
  X,
  Edit,
  type LucideProps
} from 'lucide-react';

export const LucideIcons = {
  edit: Edit,
  user: User,
  lock: Lock,
  pieChart: PieChart,
  clock: Clock,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  spinner: Loader2,
  checkCircle: CheckCircle2,
  alertCircle: AlertCircle,
  refresh: RefreshCw,
  key: KeyRound,
  shield: ShieldCheck,
  check: Check,
  search: Search,
  layoutGrid: LayoutGrid,
  list: List,
  table: Table,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  zap: Zap,
  plus: Plus,
  moreVertical: MoreVertical,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  helpCircle: HelpCircle,
  users: Users,
  settings: Settings,
  fileText: FileText,
  building: Building,
  mapPin: MapPin,
  calendar: Calendar,
  briefcase: Briefcase,
  logOut: LogOut,
  menu: Menu,
  grid: Grid,
  filter: Filter,
  sliders: SlidersHorizontal,
  close: X,
};

export type LucideIconName = keyof typeof LucideIcons;
export type { LucideProps };
